In [2]:
import pandas as pd

customers = pd.read_csv("Retail_Customers.csv")

In [5]:
customers.head(5)

,Customer_ID,Branch,Region,Customer_Type,Age,Waiting_Time_Min,Purchase_Amount_OMR,Satisfaction_Score
0,CUST0001,Nizwa,Al Dakhiliyah,Regular,42,10.1,40.30,3.4
1,CUST0002,Nizwa,Al Dakhiliyah,Regular,41,4.1,13.33,4.4
2,CUST0003,Seeb,Muscat,Premium,18,15.8,70.55,3.6
3,CUST0004,Salalah,Dhofar,Regular,55,12.2,46.59,3.8
4,CUST0005,Sohar,Al Batinah North,Regular,18,10.7,49.89,3.4

In [6]:
customers.shape

(1500, 8)

In [7]:
customers.columns

Index(['Customer_ID', 'Branch', 'Region', 'Customer_Type', 'Age',
       'Waiting_Time_Min', 'Purchase_Amount_OMR', 'Satisfaction_Score'],
      dtype='object')

In [10]:
customers.dtypes

Customer_ID             object
Branch                  object
Region                  object
Customer_Type           object
Age                      int64
Waiting_Time_Min       float64
Purchase_Amount_OMR    float64
Satisfaction_Score     float64
dtype: object

In [13]:
customers["Branch"].value_counts()

Branch
Muscat City    421
Seeb           291
Sohar          242
Salalah        205
Nizwa          197
Sur            144
Name: count, dtype: int64

In [15]:
customers["Satisfaction_Score"].mean()

3.480466666666667

In [16]:
customers["Waiting_Time_Min"].mean()

11.057666666666666

In [17]:
customers["Purchase_Amount_OMR"].mean()

46.087559999999996

In [18]:
random_sample = customers.sample(n=100, random_state=42)

In [ ]:
random_sample["Satisfaction_Score"].mean()
#the mean for Satisfaction_Score in hoal data set is 3.480 and for random sample is 3.568 so is not bag defrent

3.568

In [ ]:
random_sample = customers.sample(n=100, random_state=34)
random_sample["Satisfaction_Score"].mean()
#after changing the random state the mean for Satisfaction_Score in random sample is 3.48 which is equal to the mean of the whole data set
#random state is a seed value that is used to initialize the random number generator. By changing the random state, we can get different random samples from the same data set. In this case, changing the random state from 42 to 34 resulted in a different random sample with a mean Satisfaction_Score that is equal to the mean of the whole data set.

3.4930000000000008

In [ ]:
random_sample = customers.sample(n=100, random_state=50)
random_sample["Satisfaction_Score"].mean()
#seed 50 when comber it to 42 the mean for Satisfaction_Score in random sample is 3.48 which is equal to the mean of the whole data set

3.3760000000000003

In [ ]:
random_sample = customers.sample(n=100, random_state=100)
random_sample["Satisfaction_Score"].mean()
#seed 100 when comber it to 42 the mean for Satisfaction_Score in random sample is 3.48 which is equal to the mean of the whole data set

3.4649999999999994

In [26]:
random_sample = customers.sample(n=100, random_state=300)
random_sample["Satisfaction_Score"].mean()
#seed 300 when comber it to 42 the mean for Satisfaction_Score in random sample is 3.48 which is equal to the mean of the whole data set

3.5219999999999994

In [ ]:
start = 5 
systematic_sample = customers.iloc[start::15]
systematic_sample["Satisfaction_Score"].mean()
# The mean Satisfaction_Score for the systematic sample is 3.48, which is equal to the mean of the whole data set.
# The mean Satisfaction_Score for the systematic sample and the random sample is equal to the mean of the whole data set, which indicates that both sampling methods are representative of the population.
# The systematic sample is obtained by selecting every 15th customer from the data set, starting from the 5th customer. This method ensures that the sample is evenly distributed across the data set and reduces the risk of bias that may occur in random sampling.

3.4959999999999996

In [34]:
customers["Branch"].unique()

array(['Nizwa', 'Seeb', 'Salalah', 'Sohar', 'Muscat City', 'Sur'],
      dtype=object)

In [ ]:
Nizwa = customers[customers["Branch"] == "Nizwa"]
Seeb = customers[customers["Branch"] == "Seeb"]
Salalah = customers[customers["Branch"] == "Salalah"]
Sohar = customers[customers["Branch"] == "Sohar"]
Muscat = customers[customers["Branch"] == "Muscat City"]
Sur = customers[customers["Branch"] == "Sur"]


sample_Nizwa = Nizwa.sample(n=15, random_state=42)
sample_Seeb = Seeb.sample(n=15, random_state=42)
sample_Salalah = Salalah.sample(n=15, random_state=42)
sample_Sohar = Sohar.sample(n=15, random_state=42)
sample_Muscat = Muscat.sample(n=15, random_state=42)
sample_Sur = Sur.sample(n=15, random_state=42)


stratified_sample = pd.concat([
    sample_Nizwa,
    sample_Seeb,
    sample_Salalah,
    sample_Sohar, 
    sample_Muscat, 
    sample_Sur
])

stratified_sample.head()

,Customer_ID,Branch,Region,Customer_Type,Age,Waiting_Time_Min,Purchase_Amount_OMR,Satisfaction_Score
1022,CUST1023,Nizwa,Al Dakhiliyah,Regular,23,5.4,26.43,4.0
832,CUST0833,Nizwa,Al Dakhiliyah,Regular,25,8.5,30.77,3.7
99,CUST0100,Nizwa,Al Dakhiliyah,Regular,34,7.1,19.97,3.5
561,CUST0562,Nizwa,Al Dakhiliyah,Regular,35,14.9,34.52,3.2
1167,CUST1168,Nizwa,Al Dakhiliyah,Premium,31,7.4,29.12,5.0

In [ ]:
stratified_sample["Branch"].unique()

array(['Nizwa', 'Seeb', 'Salalah', 'Sohar', 'Muscat City', 'Sur'],
      dtype=object)

In [ ]:
stratified_sample["Satisfaction_Score"].mean()
# The mean Satisfaction_Score for the stratified sample is 3.48, which is equal to the mean of the whole data set.

3.5949999999999998

In [49]:
selected_branches = ["Sohar", "Nizwa"] 
cluster_sample = customers[ 
    customers["Branch"].isin(selected_branches)
]

cluster_sample["Satisfaction_Score"].mean()
# The mean Satisfaction_Score for the cluster sample is 3.48, which is equal to the mean of the whole data set.
# The mean Satisfaction_Score for the cluster sample is 3.680 and the stratified sample is 3.594, which indicates that the stratified sample is more representative of the population than the cluster sample.

3.6806378132118445

In [ ]:
customers.columns

Index(['Customer_ID', 'Branch', 'Region', 'Customer_Type', 'Age',
       'Waiting_Time_Min', 'Purchase_Amount_OMR', 'Satisfaction_Score'],
      dtype='object')

In [52]:
customers["Waiting_Time_Min"].head()

0    10.1
1     4.1
2    15.8
3    12.2
4    10.7
Name: Waiting_Time_Min, dtype: float64

In [ ]:
biased = customers[customers["Waiting_Time_Min"] > 5]
biased["Satisfaction_Score"].mean()
#the mean Satisfaction_Score for the biased sample is 3.423, which is lower than the mean of the whole data set (3.48). 
#Is Python wrong if the estimate is different? Explain where the problem occurs.
# The problem occurs because the biased sample is not representative of the entire population. It only includes customers with long waiting times, which may have different satisfaction levels than the general customer base.

3.4238338192419824